[PROTOCOLS]
Flexibility Hub = [
    {"tag": "section", "text": "Landscape estimation", "children": [
        {"tag": "protocol_group", "text": "Deformation field", "openItem": "True", "children": [
            {"tag": "protocol_group", "text": "Zernike3Deep", "openItem": "False", "children": [
                {"tag": "protocol", "value": "JaxProtTrainZernike3Deep", "text": "default"}
            ]}
        ]},
        {"tag": "protocol_group", "text": "Heterogeneous reconstruction", "openItem": "True", "children": [
            {"tag": "protocol_group", "text": "HetSIREN", "openItem": "False", "children": [
                {"tag": "protocol", "value": "JaxProtFlexibleAlignmentHetSiren", "text": "default"},
                {"tag": "protocol", "value": "JaxProtPredictHetSiren", "text": "default"}
            ]}
        ]}
    ]},
    {"tag": "section", "text": "Landscape consensus", "children": [
        {"tag": "protocol", "value": "JaxProtTrainFlexConsensus", "text": "default"},
        {"tag": "protocol", "value": "JaxProtInteractiveFlexConsensus", "text": "default"}
    ]},
    {"tag": "section", "text": "Data analysis", "children": [
        {"tag": "protocol", "value": "JaxProtFilterLatents", "text": "default"},
        {"tag": "protocol", "value": "JaxProtAnnotateSpace", "text": "default"}
    ]},
    {"tag": "section", "text": "Map reconstruction", "children": [
        {"tag": "protocol_group", "text": "MoDART", "openItem": "False", "children": [
            {"tag": "protocol", "value": "JaxProtReconstructMoDART", "text": "default"}
        ]},
        {"tag": "protocol_group", "text": "ReconSIREN", "openItem": "False", "children": [
            {"tag": "protocol", "value": "JaxProtAngularAlignmentReconSiren", "text": "default"}
        ]}
    ]},
    {"tag": "section", "text": "Gray level adjustment", "children": [
        {"tag": "protocol", "value": "JaxProtImageAdjustment", "text": "default"},
        {"tag": "protocol", "value": "JaxProtVolumeAdjustment", "text": "default"}
    ]}
 ]