# **************************************************************************
# *
# * Authors:  David Herreros (dherreros@cnb.csic.es)
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************


import os
from glob import glob
import time
import subprocess
import multiprocessing as mp
import psutil
import socket
import webbrowser
from contextlib import closing

from pyworkflow.viewer import DESKTOP_TKINTER, WEB_DJANGO
from pyworkflow.gui.dialog import showError

from pwem.viewers import DataViewer

from hax.protocols import (JaxProtFlexibleAlignmentHetSiren, JaxProtTrainFlexConsensus, JaxProtAngularAlignmentReconSiren,
                           JaxProtImageAdjustment, JaxProtVolumeAdjustment)

import hax


class JaxTensorboardViewer(DataViewer):
    """ Tensorboard visualization of neural networks """
    _label = 'viewer Tensorboard'
    _targets = [JaxProtFlexibleAlignmentHetSiren,
                JaxProtTrainFlexConsensus,
                JaxProtAngularAlignmentReconSiren,
                JaxProtImageAdjustment,
                JaxProtVolumeAdjustment]
    _environments = [DESKTOP_TKINTER, WEB_DJANGO]

    def __init__(self, **kwargs):
        DataViewer.__init__(self, **kwargs)
        self._data = None

    def _visualize(self, obj, **kwargs):
        logdir_path = glob(self.protocol._getExtraPath("*_metrics/"))[0]

        def launchTensorboard(logdir_path):
            def is_port_in_use(port: int) -> bool:
                with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                    return s.connect_ex(('localhost', port)) == 0

            # Find free port
            with closing(socket.socket(socket.AF_INET, socket.SOCK_STREAM)) as s:
                s.bind(('', 0))
                s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
                port = s.getsockname()[1]

            # Launch TensorBoard
            program = hax.Plugin.getProgram("tensorboard", gpu=None, uses_project_manager=False)
            args = f" --logdir {logdir_path} --port {port}"
            self.tensorboard_process = subprocess.Popen(program + args, shell=True)
            while not is_port_in_use(port):
                time.sleep(0.1)

            url = f"http://localhost:{port}/"
            print(f"TensorBoard running at {url}")

            # Use webbrowser.get() to obtain command
            try:
                browser_controller = webbrowser.get()  # get default browser
                browser_cmd = browser_controller.name
            except webbrowser.Error:
                browser_cmd = None

            # Launch the browser manually if we can
            if browser_cmd:
                browser_proc = subprocess.Popen([browser_cmd, url])
                print(f"Opened {browser_cmd} for TensorBoard view")
            else:
                webbrowser.open_new(url)
                browser_proc = None
                print("Opened browser via webbrowser, but cannot track its closure")

            # Wait for browser to close
            if browser_proc:
                browser_proc.wait()
                print("Browser closed — stopping TensorBoard...")
            else:
                print("Cannot detect browser closure — press Ctrl+C to stop TensorBoard manually.")

            # Stop TensorBoard
            parent = psutil.Process(self.tensorboard_process.pid)
            for child in parent.children(recursive=True):
                child.kill()
            self.tensorboard_process.terminate()
            self.tensorboard_process.wait()
            print("TensorBoard stopped.")

        if not os.path.isdir(logdir_path):
            if hasattr(self.protocol, "tensorboard"):
                if not self.protocol.tensorboard.get():
                    msg = ("Tensorboard cannot be opened because the option \"Allow Tensorboard visualization\" "
                           "in the protocol form has been set to \"No\". If you want to visualize one of the "
                           "outputs generated by this protocol, please, right click on the deried output from the "
                           "output list and choose the desired viewer to open it.")
            else:
                msg = "Tensorboard log files have not been properly generated."
            showError(title="Tensorboard log files not found", msg=msg, parent=self.getTkRoot())
            return []

        p = mp.Process(target=launchTensorboard, args=(logdir_path,), daemon=True)
        p.start()

        return []
