# **************************************************************************
# *
# * Authors:     David Herreros Calero (dherreros@cnb.csic.es)
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************


import os
import shutil
import numpy as np
from glob import glob
from xmipp_metadata.image_handler import ImageHandler

from pyworkflow import NEW, VERSION_1
from pyworkflow.protocol import LEVEL_ADVANCED
from pyworkflow.protocol.params import PointerParam, IntParam, BooleanParam, StringParam, USE_GPU, GPU_LIST
import pyworkflow.utils as pwutils
from pyworkflow.utils.properties import Message
from pyworkflow.gui.dialog import askYesNo
from pyworkflow.object import Integer

from pwem.protocols import ProtAnalysis3D, ProtFlexBase
from pwem.objects import ClassFlex, VolumeFlex, SetOfClassesFlex

import hax
from hax.utils import getOutputSuffix
from hax.annotate_space_functions.annotate_space_arguments import getReducedSpaceArguments


class JaxProtAnnotateSpace(ProtAnalysis3D, ProtFlexBase):
    """
    Interactive annotation of conformational spaces.

    AI Generated:

    Annotate Space (JaxProtAnnotateSpace) — User Manual
        Overview

        The Annotate Space protocol provides an interactive environment for exploring and annotating
        conformational landscapes that have previously been learned by flexible cryo-EM reconstruction
        methods. Its main purpose is to transform an abstract latent representation into biologically
        interpretable structural classes by allowing the user to inspect the organization of the latent
        space, identify regions of interest, and assign particles to meaningful conformational groups.

        In practical cryo-EM workflows, flexible reconstruction methods often describe structural
        heterogeneity as a continuous latent manifold rather than a discrete classification. While this
        representation captures rich conformational variability, biological interpretation often requires
        identifying specific states, transitions, or families of related conformations. This protocol
        bridges that gap by enabling interactive selection of latent regions and converting those
        selections into classes and representative volumes.

        Inputs and General Workflow

        The protocol requires a set of flexible particles as input. These particles must already contain
        latent coordinates generated by a compatible flexible reconstruction framework such as HetSIREN,
        Zernike3D, Dynamight, Opus-DSD, CryoDRGN, or cryoSPARC. Each particle is represented in latent
        space by a coordinate that reflects its position within the conformational landscape.

        During execution, the protocol first extracts the latent coordinates of all particles and writes
        them into an intermediate representation used by the interactive annotation engine. The protocol
        then launches a dedicated visualization session where the latent space can be explored. Depending
        on the reconstruction program that generated the input particles, additional program-specific
        information is automatically supplied so that latent positions can be linked to decoded volumes
        or structural representatives.

        If the particle set also contains a reduced latent representation, such as the consensus
        embedding generated by dimensionality-reduction methods, that reduced space can also be used
        during annotation. This is particularly useful when high-dimensional latent spaces are difficult
        to interpret directly.

        Interactive Exploration of Conformational Landscapes

        The biological value of this protocol lies in its interactive nature. Rather than imposing an
        automatic clustering strategy, it allows the user to visually inspect the latent landscape and
        define regions according to structural intuition, prior biological knowledge, or observed
        transitions.

        This is especially important in heterogeneous systems where conformational variability may not be
        naturally organized into sharply separated clusters. Flexible domains, continuous motions,
        partially populated intermediates, and branching conformational pathways often require a more
        interpretive approach than conventional classification.

        By allowing selections directly in latent space, the protocol makes it possible to isolate
        biologically meaningful conformations even when the global organization of the manifold is
        complex or nonuniform.

        Program-Specific Structural Integration

        The protocol automatically adapts its behavior to the flexible reconstruction framework from
        which the input particles originate. For methods such as HetSIREN or Zernike3D, the appropriate
        reconstruction metadata are passed so that structural decoding remains consistent with the
        original model. For packages such as Dynamight, Opus-DSD, CryoDRGN, or cryoSPARC, the
        corresponding program-specific arguments are also prepared automatically.

        When available, ChimeraX integration can also be enabled. This allows the interactive latent
        exploration to be coupled directly with structural visualization, making the annotation process
        more intuitive from a biological standpoint. Instead of selecting latent regions purely from
        geometric patterns, the user can relate those regions to actual structural differences.

        For CryoDRGN-derived spaces, a box size parameter can be provided for visualization purposes.
        This ensures that representative decoded volumes are resampled to a convenient dimension without
        modifying the original reconstruction results.

        Creation of Annotated Classes

        Once the interactive session produces saved selections, the protocol converts those selections
        into new biological outputs. Each selected region becomes a flexible class associated with a
        representative volume and a subset of particles belonging to that region.

        The protocol automatically reads the particle indices corresponding to each selection and assigns
        those particles to newly created classes. At the same time, representative volumes generated
        during the annotation process are imported, resampled when necessary, and stored with the
        correct sampling information.

        This conversion is important because it transforms an exploratory latent-space operation into a
        standard cryo-EM object that can be used by downstream tools. The resulting classes can be
        inspected, compared, visualized, or used as the basis for further structural analysis.

        Outputs and Their Interpretation

        The main outputs are a set of annotated flexible classes and a corresponding set of
        representative volumes. Each class contains the particles assigned during interactive
        annotation, while each representative volume summarizes the structural identity of that selected
        conformational region.

        Biologically, these outputs often correspond to discrete conformational states, stable branches
        of a continuous landscape, or manually selected intermediates. Unlike automatic classification,
        the resulting classes reflect user-guided interpretation of the conformational manifold.

        Because the original particle metadata are preserved, the annotated outputs remain directly
        connected to the initial reconstruction workflow. This makes it possible to trace the origin of
        each selected state and compare it with the global latent landscape.

        Practical Recommendations

        In most biological applications, it is useful to begin by examining the global organization of
        the latent space before defining any selections. Dense regions often correspond to dominant
        conformational states, while elongated trajectories or bridges may indicate continuous motions or
        transition pathways.

        Users should avoid interpreting every visible separation as biologically meaningful. Sparse
        regions can reflect noise, reconstruction uncertainty, or limited sampling rather than genuine
        structural intermediates. Whenever possible, latent-space selections should be validated by
        inspecting the associated representative volumes.

        For systems with strong flexibility, it is often better to define broad conformational regions
        first and refine them later rather than attempting overly fine-grained manual classification in
        a single pass.

        Final Perspective

        For flexible cryo-EM analysis, interactive annotation is often the step where abstract latent
        geometry becomes biologically interpretable structure. By connecting latent coordinates,
        structural representatives, and particle subsets within a unified workflow, the protocol allows
        researchers to move from continuous conformational landscapes toward explicit structural states.
        Used carefully, it becomes a powerful interpretive layer between flexible reconstruction and
        biological understanding.
    """

    _label = 'annotate space'
    _devStatus = NEW
    _lastUpdateVersion = VERSION_1
    OUTPUT_PREFIX = 'flexible3DClasses'
    OUTPUT_PREFIX_CLASSES = 'flexible3DClasses'
    OUTPUT_PREFIX_VOLUMES = 'flexible3DVolumes'

    # --------------------------- DEFINE param functions ----------------------
    def _defineParams(self, form):
        form.addSection(label='General parameters')
        form.addHidden(USE_GPU, BooleanParam, default=True,
                       label="Use GPU for execution",
                       help="This protocol has both CPU and GPU implementation.\
                                     Select the one you want to use.")
        form.addHidden(GPU_LIST, StringParam, default='0',
                       expertLevel=LEVEL_ADVANCED,
                       label="Choose GPU IDs",
                       help="Add a list of GPU devices that can be used")
        form.addParam('particles', PointerParam, label="Particles to annotate",
                      pointerClass='SetOfParticlesFlex', important=True)
        form.addParam('boxSize', IntParam, label="Box size",
                      condition="particles and particles.getFlexInfo().getProgName() == 'CryoDRGN'",
                      help="Volumes generated from the CryoDrgn network will be resampled to the "
                           "chosen box size (only for the visualization).")

    # --------------------------- INSERT steps functions ----------------------
    def _insertAllSteps(self):
        self._insertFunctionStep(self.launchVolumeSlicer, interactive=True)

    def _createOutput(self):
        particles = self.particles.get()
        sr = particles.getSamplingRate()
        partIds = np.array(list(particles.getIdSet())).astype(int)
        progName = particles.getFlexInfo().getProgName()

        # Get FlexHub set creation functions
        createFn = self._createSetOfClassesFlex
        createFnSet = self._createSetOfVolumesFlex

        # Create SetOfFlexClasses
        suffix = getOutputSuffix(self, SetOfClassesFlex)
        flexClasses = createFn(self.particles, suffix, progName=progName)
        flexSetVols = createFnSet(progName=progName, suffix=suffix)
        flexSetVols.setSamplingRate(sr)

        # Folder with saved results
        layers_folder = self._getExtraPath(os.path.join("Intermediate_results", "selections_layers"))

        # Populate set of classes
        clInx = 1
        newId = 1
        for layer_folder in os.listdir(layers_folder):
            if not os.path.basename(layer_folder).startswith("SHL_"):
                # Folder with saved volumes and particle indices
                if os.path.isfile(os.path.join(layers_folder, layer_folder, "representative.mrc")):
                    representative_paths = [os.path.join(layers_folder, layer_folder, "representative.mrc"),]
                    particle_ids_paths = [os.path.join(layers_folder, layer_folder, "particle_indices.txt"),]
                else:
                    representative_paths = glob(os.path.join(layers_folder, layer_folder, "representative*.mrc"))
                    particle_ids_paths = glob(os.path.join(layers_folder, layer_folder, "particle_indices*.txt"))

                for representative_path, particle_ids_path in zip(representative_paths, particle_ids_paths):
                    if "KMeans" not in layer_folder:
                        newClass = ClassFlex()
                        newClass.copyInfo(particles)
                        newClass.setObjId(clInx)
                        newClass.setHasCTF(particles.hasCTF())
                        newClass.setAcquisition(particles.getAcquisition())
                        representative = VolumeFlex(progName=progName)
                        representative.setLocation(representative_path)
                        if hasattr(representative, "setSamplingRate"):
                            representative.setSamplingRate(sr)

                        # Check if representative needs resampling and set correct sampling rate in header
                        ImageHandler().scaleSplines(representative_path, representative_path, finalDimension=particles.getXDim(), overwrite=True)
                        ImageHandler().setSamplingRate(representative_path, sr)

                        newClass.setRepresentative(representative)

                        flexSetVols.append(representative)
                        flexClasses.append(newClass)

                        # Populate images
                        enabledClass = flexClasses[newClass.getObjId()]
                        enabledClass.enableAppend()
                        particle_ids = partIds[np.loadtxt(particle_ids_path, dtype=int)]
                        for particle_id in particle_ids:
                            item = particles[int(particle_id)]
                            item._xmipp_subtomo_labels = Integer(clInx)
                            item.setObjId(newId)
                            enabledClass.append(item)
                            newId += 1

                        flexClasses.update(enabledClass)
                        clInx += 1

        # Save new output
        name_classes = self.OUTPUT_PREFIX_CLASSES + "_" + suffix
        name_volumes = self.OUTPUT_PREFIX_VOLUMES + "_" + suffix
        args = {}
        args[name_classes] = flexClasses
        args[name_volumes] = flexSetVols

        self._defineOutputs(**args)
        self._defineSourceRelation(particles, flexClasses)

    # --------------------------- STEPS functions -----------------------------
    def launchVolumeSlicer(self):
        particles = self.particles.get()
        self.num_vol = 0

        # Check whether intermediate results' folder has been created
        if not os.path.isdir(self._getExtraPath("Intermediate_results")):
            pwutils.makePath(self._getExtraPath("Intermediate_results"))

        # Get Z space
        z_space = []
        for particle in particles.iterItems():
            z_space.append(particle.getZFlex())
        z_space = np.asarray(z_space)

        # Generate files to call command line
        file_z_space = self._getExtraPath(os.path.join("Intermediate_results", "z_space.txt"))
        np.savetxt(file_z_space, z_space)

        # Get common arguments
        path = os.path.abspath(self._getExtraPath("Intermediate_results"))
        args = f"--z_space {file_z_space} --path {path} --mode {particles.getFlexInfo().getProgName()}"

        # Provide ChimeraX path if plugin is installed
        try:
            from chimera import Plugin as chimeraPlugin
            chimerax_bin_path = os.path.join(chimeraPlugin.getHome(), "bin", "ChimeraX")
            args += f" --chimerax_binary {chimerax_bin_path}"
        except ImportError:
            print("ChimeraX plugin is not installed. Annotate space connection with ChimeraX will not be available")

        # GPU id
        gpu = ','.join([str(elem) for elem in self.getGpuList()])

        # Check if program has a reduced space saved (like in FlexConsensus)
        if len(particles.getFirstItem().getZRed()) > 0:
            args += f" {getReducedSpaceArguments(particles, self._getExtraPath())}"

        # Program specific arguments
        progName = particles.getFlexInfo().getProgName()
        if progName == "Zernike3D":
            from hax.annotate_space_functions.annotate_space_arguments import getZernike3DArguments
            args += f" {getZernike3DArguments(particles)}"
        elif progName == "HetSIREN":
            from hax.annotate_space_functions.annotate_space_arguments import getHetSIRENArguments
            args += f" {getHetSIRENArguments(particles)}"
        elif progName == "Dynamight":
            from relion.dynamight.annotate_space_arguments import getAnnotateSpaceArguments
            if gpu:
                args += f" {getAnnotateSpaceArguments(particles, gpu_id=gpu)}"
            else:
                args += f" {getAnnotateSpaceArguments(particles)}"
        elif progName == "Opus-DSD":
            from opusdsd.utils.utils import getAnnotateSpaceArguments
            if gpu:
                args += f" {getAnnotateSpaceArguments(particles, gpu_id=gpu)}"
            else:
                args += f" {getAnnotateSpaceArguments(particles)}"
        elif progName == "CryoDRGN":
            from cryodrgn.utils.utils import getAnnotateSpaceArguments
            if gpu:
                args += f" {getAnnotateSpaceArguments(particles, gpu_id=gpu)}"
            else:
                args += f" {getAnnotateSpaceArguments(particles)}"
        elif progName == "cryoSPARC":
            from cryosparc2.threeDFlex.annotate_space_arguments import getAnnotateSpaceArguments
            if gpu:
                args += f" {getAnnotateSpaceArguments(particles, gpu_id=gpu)}"
            else:
                args += f" {getAnnotateSpaceArguments(particles, gpu_id=0)}"

        program = "annotate_space"
        program = hax.Plugin.getProgram(program, gpu=gpu)
        self.runJob(program, args)
        if len(glob(self._getExtraPath(os.path.join("Intermediate_results", "selections_layers*/")))) > 0:
            out_files = os.listdir(self._getExtraPath(os.path.join("Intermediate_results", "selections_layers")))
            only_shape_layers = not np.all([os.path.basename(layer_folder).startswith("SHL_") for layer_folder in out_files])
            if only_shape_layers and askYesNo(Message.TITLE_SAVE_OUTPUT, Message.LABEL_SAVE_OUTPUT, None):
                self._createOutput()

    # --------------------------- OUTPUT functions -----------------------------
    def deleteOutput(self, output):
        attrName = self.findAttributeName(output)
        output_id = attrName.split("_")[-1]
        volumes_path = self._getExtraPath(f"Output_Volumes_{output_id}")
        shutil.rmtree(volumes_path)
        super().deleteOutput(output)

    def allowsDelete(self, obj):
        return True

    # --------------------------- INFO functions -----------------------------
    def _summary(self):
        summary = []
        if self.getOutputsSize() >= 1:
            for _, outClasses in self.iterOutputAttributes():
                summary.append("Output *%s*:" % outClasses.getNameId().split('.')[1])
                summary.append("    * Total annotated classes: *%s*" % outClasses.getSize())
        else:
            summary.append("Output annotated classes not ready yet")
        return summary

    def _methods(self):
        return [
            "Interactive annotation of conformational spaces",
        ]

    # ----------------------- VALIDATE functions ----------------------------------------
    def validate(self):
        """ Try to find errors on define params. """
        errors = []
        particles = self.particles.get()

        # Check CryoDRGN boxsize parameter is set as it is mandatory (TODO: Can we set this automatically in each program with custom parameters?)
        if particles.getFlexInfo().getProgName() == 'CryoDRGN':
            if self.boxSize.get() is None:
                errors.append("Boxsize parameter needs to be set to an integer value smaller than or equal "
                              "to the boxsize used internally to train the CryoDRGN network")
            elif self.boxSize.get() % 2 != 0:
                errors.append("Boxsize parameter needs to be an even value")

        return errors
