# **************************************************************************
# *
# * Authors:     David Herreros Calero (dherreros@cnb.csic.es)
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************


import os
import shutil
import numpy as np
from glob import glob
from xmipp_metadata.image_handler import ImageHandler

from pyworkflow import NEW, VERSION_1
from pyworkflow.protocol import LEVEL_ADVANCED
from pyworkflow.protocol.params import PointerParam, IntParam, BooleanParam, StringParam, USE_GPU, GPU_LIST
import pyworkflow.utils as pwutils
from pyworkflow.utils.properties import Message
from pyworkflow.gui.dialog import askYesNo
from pyworkflow.object import Integer

from pwem.protocols import ProtAnalysis3D, ProtFlexBase
from pwem.objects import ClassFlex, VolumeFlex, SetOfClassesFlex

import hax
from hax.utils import getOutputSuffix
from hax.annotate_space_functions.annotate_space_arguments import getReducedSpaceArguments


class JaxProtAnnotateSpace(ProtAnalysis3D, ProtFlexBase):
    """
    Interactive annotation of conformational spaces. The protocol allows
    users to explore latent conformational landscapes generated by
    flexible reconstruction methods and define biologically meaningful
    regions or classes directly in the reduced-dimensionality space.

    AI Generated:

    Annotate Space (JaxProtAnnotateSpace) — User Manual
        Overview

        The Annotate Space protocol provides an interactive environment
        for exploring conformational landscapes obtained from flexible
        cryo-EM analysis methods. Instead of operating directly on
        reconstructed volumes, the protocol works on the latent
        conformational coordinates associated with particles and allows
        users to define regions of interest, clusters, or structural
        states directly in that reduced space.

        In biological terms, this protocol is particularly useful when
        the dataset represents continuous or discrete structural
        heterogeneity. Rather than forcing the data into a predefined
        classification scheme, the protocol enables users to inspect
        conformational trajectories and manually identify biologically
        relevant states.

        Inputs and General Workflow

        The protocol requires as input a SetOfParticlesFlex object.
        These particles must contain latent-space coordinates produced by
        a compatible flexible reconstruction method such as Zernike3D,
        HetSIREN, Dynamight, Opus-DSD, CryoDRGN, or cryoSPARC 3D Flex.

        The workflow begins by extracting the latent coordinates
        associated with each particle and saving them into an
        intermediate representation. These coordinates define the
        conformational landscape that will be visualized in the
        interactive annotation interface.

        Once launched, the user explores the latent space and selects
        regions corresponding to conformational states or structural
        transitions. These selections are saved as intermediate folders
        containing representative volumes and the corresponding particle
        indices.

        Interactive Conformational Exploration

        The central feature of this protocol is the interactive
        visualization of the conformational manifold. Instead of purely
        automated clustering, users can visually inspect the latent
        landscape and define classes based on structural intuition,
        biological relevance, or observed trajectories.

        This is particularly important in cryo-EM studies where
        conformational changes are often continuous rather than sharply
        separated. In such cases, manual annotation can reveal
        transitions between states, flexible motions, or local regions
        of structural variability that standard classification methods
        may fail to isolate.

        Program-Specific Compatibility

        The protocol adapts automatically to the flexible reconstruction
        method used to generate the latent coordinates.

        For Zernike3D and HetSIREN, method-specific arguments are added
        so the annotation interface correctly interprets the latent
        space.

        For Dynamight, Opus-DSD, CryoDRGN, and cryoSPARC, dedicated
        helper functions provide the required metadata so that
        annotation remains consistent with the original reconstruction
        framework.

        This flexibility makes the protocol a common annotation layer
        across several heterogeneous flexibility-analysis pipelines.

        Reduced Spaces and Advanced Integration

        If the input particles contain reduced latent coordinates
        (ZRed), the protocol automatically detects and incorporates
        them. This is especially relevant in workflows where dimensional
        reduction has already been performed upstream, such as in
        consensus or embedding-based analyses.

        When available, the protocol can also connect to ChimeraX,
        allowing structural visualization to be integrated with latent
        space inspection. This creates a particularly useful bridge
        between abstract conformational coordinates and direct map-based
        structural interpretation.

        Output Generation and Biological Interpretation

        After annotation, the protocol can generate two main outputs:

        1. A SetOfClassesFlex object containing the annotated particle
           classes.

        2. A SetOfVolumesFlex object containing representative volumes
           associated with each annotated class.

        For each selected region, the protocol identifies the particles
        belonging to that region and associates them with a
        representative volume. These representative maps are resampled
        when necessary so they remain consistent with the original
        particle dimensions and sampling rate.

        From a biological perspective, each output class represents a
        user-defined conformational state. Unlike purely statistical
        clustering, these classes often reflect structural hypotheses
        driven by prior biological knowledge or by direct visual
        inspection of the conformational continuum.

        CryoDRGN-Specific Considerations

        When the input particles come from CryoDRGN, the box size
        parameter becomes mandatory.

        This parameter controls how representative volumes are
        resampled for visualization. It does not affect the original
        latent embedding itself, but it is important for ensuring that
        the displayed maps remain physically meaningful.

        The box size must be an even integer and should not exceed the
        internal box size used during CryoDRGN training.

        Practical Recommendations

        In routine practice, it is often useful to begin by visually
        exploring the overall shape of the latent space before defining
        classes.

        Broad selections can first be used to identify major
        conformational branches. Once these large-scale regions are
        understood, more refined selections may isolate subtle
        structural transitions or local substates.

        Because the protocol allows direct human interaction, it is
        especially powerful when studying continuous heterogeneity,
        domain motions, flexible assemblies, or ligand-induced
        conformational changes.

        Users should keep in mind that latent proximity does not always
        imply direct structural similarity. Whenever possible,
        representative volumes should be inspected carefully before
        assigning biological interpretation.

        Outputs and Their Interpretation

        The final outputs preserve both the particle membership and the
        representative structural maps associated with each annotated
        region.

        This makes the protocol particularly useful for downstream
        analyses such as focused refinement, structural comparison,
        conformational trajectory analysis, or biological interpretation
        of dynamic ensembles.

        Final Perspective

        For cryo-EM studies of structural flexibility, annotation of
        conformational space is often more than a visualization step.
        It is a biologically guided interpretation stage where the user
        transforms an abstract latent manifold into structurally and
        functionally meaningful conformational classes.

        Careful annotation, combined with thoughtful inspection of
        representative maps, can reveal structural states and dynamic
        transitions that may otherwise remain hidden in purely automated
        analyses.
    """

    _label = 'annotate space'
    _devStatus = NEW
    _lastUpdateVersion = VERSION_1
    OUTPUT_PREFIX = 'flexible3DClasses'
    OUTPUT_PREFIX_CLASSES = 'flexible3DClasses'
    OUTPUT_PREFIX_VOLUMES = 'flexible3DVolumes'

    # --------------------------- DEFINE param functions ----------------------
    def _defineParams(self, form):
        form.addSection(label='General parameters')
        form.addHidden(USE_GPU, BooleanParam, default=True,
                       label="Use GPU for execution",
                       help="This protocol has both CPU and GPU implementation.\
                                     Select the one you want to use.")
        form.addHidden(GPU_LIST, StringParam, default='0',
                       expertLevel=LEVEL_ADVANCED,
                       label="Choose GPU IDs",
                       help="Add a list of GPU devices that can be used")
        form.addParam('particles', PointerParam, label="Particles to annotate",
                      pointerClass='SetOfParticlesFlex', important=True)
        form.addParam('boxSize', IntParam, label="Box size",
                      condition="particles and particles.getFlexInfo().getProgName() == 'CryoDRGN'",
                      help="Volumes generated from the CryoDrgn network will be resampled to the "
                           "chosen box size (only for the visualization).")

    # --------------------------- INSERT steps functions ----------------------
    def _insertAllSteps(self):
        self._insertFunctionStep(self.launchVolumeSlicer, interactive=True)

    def _createOutput(self):
        particles = self.particles.get()
        sr = particles.getSamplingRate()
        partIds = np.array(list(particles.getIdSet())).astype(int)
        progName = particles.getFlexInfo().getProgName()

        # Get FlexHub set creation functions
        createFn = self._createSetOfClassesFlex
        createFnSet = self._createSetOfVolumesFlex

        # Create SetOfFlexClasses
        suffix = getOutputSuffix(self, SetOfClassesFlex)
        flexClasses = createFn(self.particles, suffix, progName=progName)
        flexSetVols = createFnSet(progName=progName, suffix=suffix)
        flexSetVols.setSamplingRate(sr)

        # Folder with saved results
        layers_folder = self._getExtraPath(os.path.join("Intermediate_results", "selections_layers"))

        # Populate set of classes
        clInx = 1
        newId = 1
        for layer_folder in os.listdir(layers_folder):
            if not os.path.basename(layer_folder).startswith("SHL_"):
                # Folder with saved volumes and particle indices
                if os.path.isfile(os.path.join(layers_folder, layer_folder, "representative.mrc")):
                    representative_paths = [os.path.join(layers_folder, layer_folder, "representative.mrc"),]
                    particle_ids_paths = [os.path.join(layers_folder, layer_folder, "particle_indices.txt"),]
                else:
                    representative_paths = glob(os.path.join(layers_folder, layer_folder, "representative*.mrc"))
                    particle_ids_paths = glob(os.path.join(layers_folder, layer_folder, "particle_indices*.txt"))

                for representative_path, particle_ids_path in zip(representative_paths, particle_ids_paths):
                    if "KMeans" not in layer_folder:
                        newClass = ClassFlex()
                        newClass.copyInfo(particles)
                        newClass.setObjId(clInx)
                        newClass.setHasCTF(particles.hasCTF())
                        newClass.setAcquisition(particles.getAcquisition())
                        representative = VolumeFlex(progName=progName)
                        representative.setLocation(representative_path)
                        if hasattr(representative, "setSamplingRate"):
                            representative.setSamplingRate(sr)

                        # Check if representative needs resampling and set correct sampling rate in header
                        ImageHandler().scaleSplines(representative_path, representative_path, finalDimension=particles.getXDim(), overwrite=True)
                        ImageHandler().setSamplingRate(representative_path, sr)

                        newClass.setRepresentative(representative)

                        flexSetVols.append(representative)
                        flexClasses.append(newClass)

                        # Populate images
                        enabledClass = flexClasses[newClass.getObjId()]
                        enabledClass.enableAppend()
                        particle_ids = partIds[np.loadtxt(particle_ids_path, dtype=int)]
                        for particle_id in particle_ids:
                            item = particles[int(particle_id)]
                            item._xmipp_subtomo_labels = Integer(clInx)
                            item.setObjId(newId)
                            enabledClass.append(item)
                            newId += 1

                        flexClasses.update(enabledClass)
                        clInx += 1

        # Save new output
        name_classes = self.OUTPUT_PREFIX_CLASSES + "_" + suffix
        name_volumes = self.OUTPUT_PREFIX_VOLUMES + "_" + suffix
        args = {}
        args[name_classes] = flexClasses
        args[name_volumes] = flexSetVols

        self._defineOutputs(**args)
        self._defineSourceRelation(particles, flexClasses)

    # --------------------------- STEPS functions -----------------------------
    def launchVolumeSlicer(self):
        particles = self.particles.get()
        self.num_vol = 0

        # Check whether intermediate results' folder has been created
        if not os.path.isdir(self._getExtraPath("Intermediate_results")):
            pwutils.makePath(self._getExtraPath("Intermediate_results"))

        # Get Z space
        z_space = []
        for particle in particles.iterItems():
            z_space.append(particle.getZFlex())
        z_space = np.asarray(z_space)

        # Generate files to call command line
        file_z_space = self._getExtraPath(os.path.join("Intermediate_results", "z_space.txt"))
        np.savetxt(file_z_space, z_space)

        # Get common arguments
        path = os.path.abspath(self._getExtraPath("Intermediate_results"))
        args = f"--z_space {file_z_space} --path {path} --mode {particles.getFlexInfo().getProgName()}"

        # Provide ChimeraX path if plugin is installed
        try:
            from chimera import Plugin as chimeraPlugin
            chimerax_bin_path = os.path.join(chimeraPlugin.getHome(), "bin", "ChimeraX")
            args += f" --chimerax_binary {chimerax_bin_path}"
        except ImportError:
            print("ChimeraX plugin is not installed. Annotate space connection with ChimeraX will not be available")

        # GPU id
        gpu = ','.join([str(elem) for elem in self.getGpuList()])

        # Check if program has a reduced space saved (like in FlexConsensus)
        if len(particles.getFirstItem().getZRed()) > 0:
            args += f" {getReducedSpaceArguments(particles, self._getExtraPath())}"

        # Program specific arguments
        progName = particles.getFlexInfo().getProgName()
        if progName == "Zernike3D":
            from hax.annotate_space_functions.annotate_space_arguments import getZernike3DArguments
            args += f" {getZernike3DArguments(particles)}"
        elif progName == "HetSIREN":
            from hax.annotate_space_functions.annotate_space_arguments import getHetSIRENArguments
            args += f" {getHetSIRENArguments(particles)}"
        elif progName == "Dynamight":
            from relion.dynamight.annotate_space_arguments import getAnnotateSpaceArguments
            if gpu:
                args += f" {getAnnotateSpaceArguments(particles, gpu_id=gpu)}"
            else:
                args += f" {getAnnotateSpaceArguments(particles)}"
        elif progName == "Opus-DSD":
            from opusdsd.utils.utils import getAnnotateSpaceArguments
            if gpu:
                args += f" {getAnnotateSpaceArguments(particles, gpu_id=gpu)}"
            else:
                args += f" {getAnnotateSpaceArguments(particles)}"
        elif progName == "CryoDRGN":
            from cryodrgn.utils.utils import getAnnotateSpaceArguments
            if gpu:
                args += f" {getAnnotateSpaceArguments(particles, gpu_id=gpu)}"
            else:
                args += f" {getAnnotateSpaceArguments(particles)}"
        elif progName == "cryoSPARC":
            from cryosparc2.threeDFlex.annotate_space_arguments import getAnnotateSpaceArguments
            if gpu:
                args += f" {getAnnotateSpaceArguments(particles, gpu_id=gpu)}"
            else:
                args += f" {getAnnotateSpaceArguments(particles, gpu_id=0)}"

        program = "annotate_space"
        program = hax.Plugin.getProgram(program, gpu=gpu)
        self.runJob(program, args)
        if len(glob(self._getExtraPath(os.path.join("Intermediate_results", "selections_layers*/")))) > 0:
            out_files = os.listdir(self._getExtraPath(os.path.join("Intermediate_results", "selections_layers")))
            only_shape_layers = not np.all([os.path.basename(layer_folder).startswith("SHL_") for layer_folder in out_files])
            if only_shape_layers and askYesNo(Message.TITLE_SAVE_OUTPUT, Message.LABEL_SAVE_OUTPUT, None):
                self._createOutput()

    # --------------------------- OUTPUT functions -----------------------------
    def deleteOutput(self, output):
        attrName = self.findAttributeName(output)
        output_id = attrName.split("_")[-1]
        volumes_path = self._getExtraPath(f"Output_Volumes_{output_id}")
        shutil.rmtree(volumes_path)
        super().deleteOutput(output)

    def allowsDelete(self, obj):
        return True

    # --------------------------- INFO functions -----------------------------
    def _summary(self):
        summary = []
        if self.getOutputsSize() >= 1:
            for _, outClasses in self.iterOutputAttributes():
                summary.append("Output *%s*:" % outClasses.getNameId().split('.')[1])
                summary.append("    * Total annotated classes: *%s*" % outClasses.getSize())
        else:
            summary.append("Output annotated classes not ready yet")
        return summary

    def _methods(self):
        return [
            "Interactive annotation of conformational spaces",
        ]

    # ----------------------- VALIDATE functions ----------------------------------------
    def validate(self):
        """ Try to find errors on define params. """
        errors = []
        particles = self.particles.get()

        # Check CryoDRGN boxsize parameter is set as it is mandatory (TODO: Can we set this automatically in each program with custom parameters?)
        if particles.getFlexInfo().getProgName() == 'CryoDRGN':
            if self.boxSize.get() is None:
                errors.append("Boxsize parameter needs to be set to an integer value smaller than or equal "
                              "to the boxsize used internally to train the CryoDRGN network")
            elif self.boxSize.get() % 2 != 0:
                errors.append("Boxsize parameter needs to be an even value")

        return errors
