# **************************************************************************
# *
# * Authors:     Eduardo García Delgado (eduardo.garcia@cnb.csic.es) [1]
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC [1]
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************

import os

from xmipp_metadata.image_handler import ImageHandler

import pyworkflow.protocol.params as params
from pyworkflow import VERSION_1

from pwem.protocols import ProtAnalysis3D, ProtFlexBase
from pwem.objects import Volume, AtomStruct
import hax


class JaxProtRigidFitting(ProtAnalysis3D, ProtFlexBase):
    """ Protocol for sharpening with HetSIREN reconstruction."""
    _label = 'rigid fitting'
    _lastUpdateVersion = VERSION_1

    # --------------------------- DEFINE param functions -----------------------
    def _defineParams(self, form):
        form.addSection(label='Input')
        form.addHidden(params.USE_GPU, params.BooleanParam, default=True,
                       label="Use GPU for execution",
                       help="This protocol has both CPU and GPU implementation.\
                                 Select the one you want to use.")

        form.addHidden(params.GPU_LIST, params.StringParam, default='0',
                       expertLevel=params.LEVEL_ADVANCED,
                       label="Choose GPU IDs",
                       help="Add a list of GPU devices that can be used")

        form.addParam('inputPDB', params.PointerParam, important=True,
                       label="Atomic structure", pointerClass=AtomStruct,
                       help="Atomic structure imported as pdb or cif.")

        form.addParam('inputVolume', params.PointerParam, important=True,
                       label="Input volume", pointerClass='Volume',
                       help="Input volume for rigid fitting with atomic structure")

        form.addParam('doDownsample', params.BooleanParam, default=True,
                       label='Downsample rasterized volume?',
                       help='If your GPU is not able to fit the rasterized volume from your atomic structure when performing global rigid fitting in memory, '
                            'you can set this parameter to a certain downsampling factor. This way, you will be able to process a better and enhanced global search '
                            'at the expense of losing resolution in the volumes generated by the network.')

        form.addParam('downFactor', params.FloatParam, default=4.0,
                       condition="doDownsample",
                       label='Downsampling factor for volume',
                       help='When applying for a rigid fitting, a global search will be computed first as a previous work for later local docking.')

        form.addParam('isAligned', params.BooleanParam, default=False, label='Is already aligned?',
                      help='When set to Yes, it will be taken into account the previous alignment and, therefore, only this method will serve as a validation '
                           'for rigid fitted atomic structures into pre-aligned systems.')

        form.addParam('needsCentering', params.BooleanParam, default=False, label='Is it required centering?',
                      help='When set to Yes, it will apply a shift transformation on the atomic structure '
                           'to be on the same global frame as the volume (for example, while computing the FSC).')

        form.addParallelSection(threads=1, mpi=4)

    # --------------------------- INSERT steps functions -----------------------
    def _insertAllSteps(self):
        self._insertFunctionStep(self.rigidFittingStep)
        self._insertFunctionStep(self.createOutputStep)

    def rigidFittingStep(self):
        pdb_file = self.inputPDB.get().getFileName()
        vol_file = self.inputVolume.get().getFileName()
        out_path = self._getExtraPath('pdb_fitted')
        if not os.path.isdir(out_path):
            os.mkdir(out_path)
        sr = self.inputVolume.get().getSamplingRate()
        downFactor = self.downFactor.get()
        args = "--pdb %s --vol %s --sr %f --downfactor %f --out_dir %s " \
               % (pdb_file, vol_file,  sr, downFactor, out_path)

        if self.isAligned.get():
            args += '--is_aligned '

        if self.needsCentering.get():
            args += '--needsCentering '

        if self.useGpu.get():
            gpu = str(self.getGpuList()[0])
        else:
            gpu = ''

        program = hax.Plugin.getProgram("rigid_fitting", gpu)
        self.runJob(program, args, numberOfMpi=1)

    def createOutputStep(self):
        pdb_file = self.inputPDB.get().getFileName()
        _, ext = os.path.splitext(pdb_file)
        out_path_vol = os.path.join(self._getExtraPath('pdb_fitted'), 'final_rigid_input_norm.mrc')
        if not self.isAligned:
            out_path_pdb1 = os.path.join(self._getExtraPath('pdb_fitted'), f'final_rigid_fitted{ext.lower()}')
            out_path_pdb2 = os.path.join(self._getExtraPath('pdb_fitted'), f'final_rigid_refined_fitted{ext.lower()}')

            outputPdb1 = AtomStruct()
            outputPdb1.setFileName(out_path_pdb1)
            self._defineOutputs(outputStructure1=outputPdb1)
            outputPdb2 = AtomStruct()
            outputPdb2.setFileName(out_path_pdb2)
            self._defineOutputs(outputStructure2=outputPdb2)

        else:
            out_path_pdb = os.path.join(self._getExtraPath('pdb_fitted'), f'final_rigid_fitted{ext.lower()}')

            outputPdb = AtomStruct()
            outputPdb.setFileName(out_path_pdb)
            self._defineOutputs(outputStructure=outputPdb)

        outVol = Volume()
        outVol.setSamplingRate(self.inputVolume.get().getSamplingRate())
        outVol.setFileName(out_path_vol)
        self._defineOutputs(outputVolume=outVol)

    # --------------------------- INFO functions -----------------------------
    def _summary(self):
        summary = []
        logFile = os.path.abspath(self._getLogsPath()) + "/run.stdout"
        with open(logFile, "r") as fi:
            for ln in fi:
                if ln.startswith("GPU memory has"):
                    summary.append(ln)
                    break
        return summary

    # ----------------------- VALIDATE functions -----------------------
    def _validate(self):
        """ Try to find errors on define params. """
        errors = []

        return errors

    def _warnings(self):
        warnings = []

        return warnings