# **************************************************************************
# *
# * Authors:     Eduardo García Delgado (eduardo.garcia@cnb.csic.es) [1]
# *              David Herreros Calero (dherreos@cnb.csic.es) [1]
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC [1]
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************

import os
import numpy as np
from sklearn.cluster import KMeans

from xmipp_metadata.metadata import XmippMetaData
from xmipp_metadata.image_handler import ImageHandler

import pyworkflow.protocol.params as params
from pyworkflow.utils.path import moveFile
from pyworkflow import VERSION_1
from pyworkflow.utils import getExt, makePath

from pwem.protocols import ProtAnalysis3D, ProtFlexBase
from pwem.objects import Volume

import xmipp3
import hax


class JaxProtSharpeningHetSiren(ProtAnalysis3D, ProtFlexBase):
    """ Protocol for sharpening with HetSIREN reconstruction."""
    _label = 'sharpening - HetSIREN'
    _lastUpdateVersion = VERSION_1

    # --------------------------- DEFINE param functions -----------------------
    def _defineParams(self, form):
        form.addSection(label='Input')
        form.addHidden(params.USE_GPU, params.BooleanParam, default=True,
                       label="Use GPU for execution",
                       help="This protocol has both CPU and GPU implementation.\
                                 Select the one you want to use.")

        form.addHidden(params.GPU_LIST, params.StringParam, default='0',
                       expertLevel=params.LEVEL_ADVANCED,
                       label="Choose GPU IDs",
                       help="Add a list of GPU devices that can be used")

        group = form.addGroup("Data")
        group.addParam('numProjections', params.IntParam, important=True,
                       label="Number of particles to generate according to input volume",
                       help="Number of projections or particles to be generated by an input volume. It will extract those "
                            "particles and give them their respective angles assignment in the metadata. The more particles "
                            "generated, the more effective will be the method, but more time it will take to compute.")

        group.addParam('inputVolume', params.PointerParam, allowsNull=True,
                       label="Starting volume", pointerClass='Volume',
                       help="If not provided, HetSIREN will learn from scratch how to recover heterogeneous states. If a "
                            "volume is provided, HetSIREN will use that volume as its starting state, and learn how to "
                            "modify it towards the heterogeneous states present in the data.\n\n"
                            "When should a map be provided?\n"
                            "    - If transport mass mode is set to Yes (check Advanced parameter in Reconstruction tab), it is "
                            "advisable to provide an input map\n"
                            "    - If transport mass mode is set to Yes and "
                            "If transport mass mode is set to No and local reconstruction is enabled (check Advanced "
                            "parameter in Reconstruction tab), it is highly recommended to provide a map\n\n"
                            "When is not advisable to provide a map?\n"
                            "If transport mass and local reconstruction are ser to No (check Advanced parameter in "
                            "Reconstruction tab), we recommend leaving this  parameter empty to give HetSIREN more freedom "
                            "to denoise and learn accurate states.")

        group.addParam('inputVolumeMask', params.PointerParam,
                       label="Reconstruction mask", pointerClass='VolumeMask', allowsNull=True,
                       help="Reconstruction mask meaning will depend on the mode chosen (NOTE: masks provided here MUST "
                            "be BINARY):\n\n"
                            "Transport mass is set to Yes\n"
                            "In this case, the provided mask will determine which voxels can be moved inside the volume box. "
                            "If you have provided an input volume, you can provide here a tight mask or a dilated tight mask, as HetSIREN "
                            "will be able to move those voxels anywhere needed to recover a given heterogeneous state. If don't provide an input "
                            "volume, we recommend providing a mask with enough mass to recover all expected states. A good rule of thumb "
                            "for this case is to provide a spherical mask with radius 0.25 * box_size.\n\n"
                            "Transport mass is set to No\n"
                            "If local reconstruction is set to No, we recommend to leave this parameter empty. If local reconstruction is "
                            "enabled, you should provide here a mask enclosing your region of interest AND any region where the motion of the "
                            "protein is expected to happen. Remember that, in Reconstruction mode (i.e., Transport mass is set to No), HetSIREN "
                            "will assume voxels as fixed in space. Any motions happening outside the binary mask will NOT be considered.")

        group.addParam('doDownsample', params.BooleanParam, default=False,
                       label='Downsample the projected images before training?',
                       help='If your GPU is not able to fit the projection process of your particles in memory, you can play with this parameter to '
                            'downsample your images. In this way, you will be able to fit your projected particles at the expense of losing resolution '
                            'in the volumes generated by the network.')

        group.addParam('boxSize', params.IntParam, default=128,
                       condition="doDownsample",
                       label='Downsample volume to this box size',
                       help='If your GPU is not able to fit the projection process of your particles in memory, you can play with this parameter to '
                            'downsample your images. In this way, you will be able to fit your projected particles at the expense of losing resolution '
                            'in the volumes generated by the network.')

        group = form.addGroup("Gaussian Fitting")
        group.addParam('numberGaussians', params.IntParam, label='Fixed number of gaussians',
                       allowsNull=True,
                       help="Before training the network, HetSIREN will try to fit a set of Gaussians in the reference volume to recreate it. "
                            "The default criterium is to automatically determine the number of Gaussians needed to reproduce the reference volume "
                            "with high-fidelity. However, if you prefer to set the number of Gaussians in advance based on your own criterium (e.g., "
                            "the number of residues in your protein), you can set this parameter. When applied, the HetSIREN will fit this number of Gaussians "
                            "so that they reproduce the reference volume as well as possible.")

        group.addParam('densifyInterval', params.IntParam, default=500, label='Interval of densification',
                       allowsNull=True,
                       help='When the gaussian fitting is computed and the number of gaussians are set, the network tries to adapt this number of gaussians '
                            'based on the sizes of the gaussians and the gradients of the model. This adaptation is done by a series of '
                            'pruning and splitting processes by specific densification intervals. The number of gaussians may increase or decrease depending '
                            'on the nature of the volume and the model gradients. The bigger this interval, the less number of gaussians will be '
                            'created when finished the adaptation.')
        group.addParam('maxGaussians', params.IntParam, default=50000, label='Maximum number of gaussians',
                       allowsNull=True,
                       help='When the gaussian fitting is computed, depending on the densification interval and the initial number of gaussians, '
                            'the network may increase infinitely the total number of gaussians on the long run. This could lead to GPU overwhelming '
                            'behaviour and OOM in the later training process. The more gaussians, the bigger the risk the network will collapse. This '
                            'number is to set a limit to this computation.')

        form.addSection(label='Network')
        form.addParam('fineTune', params.BooleanParam, default=False, label='Fine tune previous network?',
                      help='When set to Yes, you will be able to provide a previously trained HetSIREN network to refine it with new '
                           'data. If set to No, you will train a new HetSIREN network from scratch.')

        form.addParam('lazyLoad', params.BooleanParam, default=False,
                      expertLevel=params.LEVEL_ADVANCED, label='Lazy loading into RAM',
                      help='If provided, images will be loaded to RAM. This is recommended if you want the best performance '
                           'and your dataset fits in your RAM memory. If this flag is not provided, '
                           'images will be memory mapped. When this happens, the program will trade disk space for performance. '
                           'Thus, during the execution additional disk space will be used and the performance '
                           'will be slightly lower compared to loading the images to RAM. Disk usage will be back to normal '
                           'once the execution has finished.')

        form.addParam('scratchFolder', params.PathParam,
                      condition="not lazyLoad",
                      label='Path to SSD scratch folder',
                      help='If you are not loading the images to RAM, we strongly recommend to provide here a path to a folder in '
                           'a SSD/NVME disk to speed up the data loading. In general, you can expected a decrease in training performance when '
                           'loading images > 256px on a HDD disk.')

        group = form.addGroup("Network hyperparameters")
        group.addParam('latDim', params.IntParam, default=10, label='Latent space dimension',
                       expertLevel=params.LEVEL_ADVANCED,
                       help="Dimension of the HetSIREN bottleneck (latent space dimension)")

        group.addParam('epochs', params.IntParam, default=50,
                       label='Number of training epochs',
                       help="Number of epochs to train the network (i.e. how many times to loop over the whole dataset "
                            "of images - set to default to 50 - as a rule of thumb, consider 50 to 100 epochs enough "
                            "for 100k images / if your dataset is bigger or smaller, scale this value proportionally to it")

        group.addParam('batchSize', params.IntParam, default=8, label='Number of images in batch',
                       help="Determines how many images will be load in the GPU at any moment during training (set by "
                            "default to 8 - you can control GPU memory usage easily by tuning this parameter to fit your "
                            "hardware requirements - we recommend using tools like nvidia-smi to monitor and/or measure "
                            "memory usage and adjust this value - keep also in mind that bigger batch sizes might be "
                            "less precise when looking for very local motions")

        group.addParam('learningRate', params.FloatParam, default=1e-4, label='Learning rate',
                       help="The learning rate (lr) sets the speed of learning. Think of the model as trying to find the "
                            "lowest point in a valley; the lr is the size of the step it takes on each attempt. A large "
                            "lr (e.g., 0.01) is like taking huge leaps ? it's fast but can be unstable, overshoot the "
                            "lowest point, or cause NAN errors. A small lr (e.g., 1e-6) is like taking tiny shuffles ? "
                            "it's stable but very slow and might get stuck before reaching the bottom. A good default is "
                            "often 0.0001. If training fails or errors explode, try making the lr 10 times smaller (e.g., "
                            "0.001 --> 0.0001).")

        group = form.addGroup("Network regularization")
        group.addParam('denoisingStrength', params.FloatParam, default=0.0, label='Denoising strength',
                       expertLevel=params.LEVEL_ADVANCED,
                       help="Determines how strongly HetSIREN will learn to remove noise from the resulting volumes. "
                            "Increasing the value of this parameter will result in a stronger regularization of the noise,"
                            " but it may affect the protein signal as well. (NOTE: We recommend setting this parameter in "
                            "the range 0.0001 to 0.1)")

        form.addParallelSection(threads=1, mpi=4)

    def _createFilenameTemplates(self):
        """ Centralize how files are called """
        myDict = {
            'imgsFn': self._getExtraPath('input_particles.xmd'),
            'imgsFnStk': self._getExtraPath('input_particles.stk'),
            'predictedFn': self._getExtraPath('predicted_latents.xmd'),
            'fnVol': self._getExtraPath('volume.mrc'),
            'fnVolMask': self._getExtraPath('mask.mrc'),
        }
        self._updateFilenamesDict(myDict)

    # --------------------------- INSERT steps functions -----------------------
    def _insertAllSteps(self):
        self._createFilenameTemplates()
        self._insertFunctionStep(self.writeMetaDataStep)
        self._insertFunctionStep(self.trainingPredictStep)
        self._insertFunctionStep(self.createOutputStep)

    def writeMetaDataStep(self):
        imgsFn = self._getFileName('imgsFn')
        imgsFnStk = self._getFileName('imgsFnStk')
        fnVol = self._getFileName('fnVol')
        fnVolMask = self._getFileName('fnVolMask')

        inputVolume = self.inputVolume.get()
        Xdim = inputVolume.getXDim()
        newXdim = self.boxSize.get() if self.doDownsample.get() else Xdim
        vol_mask_dim = newXdim

        ih = ImageHandler()
        ih.convert(self._getXmippFileName(inputVolume.getFileName()), fnVol)
        curr_vol_dim = ImageHandler(self._getXmippFileName(inputVolume.getFileName())).getDimensions()[-1]
        if curr_vol_dim != vol_mask_dim:
            self.runJob("xmipp_image_resize",
                        "-i %s --fourier %d " % (fnVol, vol_mask_dim), numberOfMpi=1,
                        env=xmipp3.Plugin.getEnviron())
        ih.setSamplingRate(fnVol, inputVolume.getSamplingRate())

        if self.inputVolumeMask.get():
            ih = ImageHandler()
            inputMask = self.inputVolumeMask.get().getFileName()
            if inputMask:
                ih.convert(self._getXmippFileName(inputMask), fnVolMask)
                curr_mask_dim = ImageHandler(self._getXmippFileName(inputMask)).getDimensions()[-1]
                if curr_mask_dim != vol_mask_dim:
                    self.runJob("xmipp_image_resize",
                                "-i %s --dim %d --interp nearest" % (fnVolMask, vol_mask_dim), numberOfMpi=1,
                                env=xmipp3.Plugin.getEnviron())
        else:
            ImageHandler().createCircularMask(fnVolMask, boxSize=vol_mask_dim, is3D=True)

        volume = ImageHandler(fnVol).scaleSplines(finalDimension=vol_mask_dim)
        particles, angles = ImageHandler().generateProjections(num_projections=self.numProjections.get(), degrees=True, pad=0, useFourier=True,
                                                             volume=volume, n_jobs=self.numberOfThreads)

        ImageHandler().write(particles, imgsFnStk)
        md = XmippMetaData(imgsFnStk, angles=angles)
        md.setMetaDataColumns(np.ones(len(md)), "subtomo_labels")
        md.write(imgsFn)

        if newXdim != Xdim:
            params = "-i %s -o %s --save_metadata_stack %s --fourier %d" % \
                     (imgsFn,
                      self._getTmpPath('scaled_particles.stk'),
                      self._getExtraPath('scaled_particles.xmd'),
                      newXdim)
            if self.numberOfMpi.get() > 1:
                params += " --mpi_job_size %d" % int(self.numProjections.get() / self.numberOfMpi.get())
            self.runJob("xmipp_image_resize", params, numberOfMpi=self.numberOfMpi.get(),
                        env=xmipp3.Plugin.getEnviron())
            moveFile(self._getExtraPath('scaled_particles.xmd'), imgsFn)

    def trainingPredictStep(self):
        md_file = self._getFileName('imgsFn')
        vol_file = self._getFileName('fnVol')
        mask_file = self._getFileName('fnVolMask')
        out_path = self._getExtraPath()
        if not os.path.isdir(out_path):
            os.mkdir(out_path)
        batch_size = self.batchSize.get()
        learningRate = self.learningRate.get()
        epochs = self.epochs.get()
        latDim = self.latDim.get()
        densifyInterval = self.densifyInterval.get()
        maxGaussians = self.maxGaussians.get()
        denoisingStrength = self.denoisingStrength.get()
        newXdim = self.boxSize.get() if self.doDownsample.get() else self.inputVolume.get().getXDim()
        correctionFactor = self.inputVolume.get().getXDim() / newXdim
        sr = correctionFactor * self.inputVolume.get().getSamplingRate()
        args = "--md %s --vol %s --sr %f --lat_dim %d --densify_interval %d --epochs %d --batch_size %d --learning_rate %s --output_path %s --denoising_strength %f " \
               % (md_file, vol_file,  sr, latDim, densifyInterval, epochs, batch_size, learningRate, out_path, denoisingStrength)

        if self.numberGaussians.get() is not None:
            args += '--num_gaussians %d ' % self.numberGaussians.get()

        if self.inputVolumeMask.get():
            args += '--mask %s ' % mask_file

        if self.lazyLoad:
            args += '--load_images_to_ram '
        else:
            if self.scratchFolder.get() is not None:
                args += '--ssd_scratch_folder %s ' % self.scratchFolder.get()

        args += '--ctf_type None --sharpening '

        if self.useGpu.get():
            gpu = str(self.getGpuList()[0])
        else:
            gpu = ''

        program = hax.Plugin.getProgram("hetsiren", gpu)
        if not os.path.isdir(self._getExtraPath("HetSIREN")):
            self.runJob(program,
                        args + f'--mode train --reload {self._getExtraPath()}'
                        if self.fineTune else args + '--mode train',
                        numberOfMpi=1)
        self.runJob(program, args + f'--mode predict --reload {self._getExtraPath()}', numberOfMpi=1)

    def createOutputStep(self):
        out_path_vol = self._getExtraPath('volume')
        model_path = self._getExtraPath('HetSIREN')
        md_file = self._getFileName('predictedFn')
        out_path = self._getExtraPath()

        metadata = XmippMetaData(md_file)
        latent_space = np.asarray([np.fromstring(item, sep=',') for item in metadata[:, 'latent_space']])

        if self.useGpu.get():
            gpu = str(self.getGpuList()[0])
        else:
            gpu = ''

        latents_kmeans = KMeans(n_clusters=1).fit(latent_space).cluster_centers_

        latents_file_txt = os.path.join(out_path, 'latents.txt')
        np.savetxt(latents_file_txt, latents_kmeans)

        if not os.path.isdir(out_path_vol):
            makePath(out_path_vol)

        args = "--latents_file %s --output_path %s --reload %s" % (latents_file_txt, out_path_vol, model_path)
        program = hax.Plugin.getProgram("decode_states_from_latents", gpu)
        self.runJob(program, args, numberOfMpi=1)

        inputVolume = self.inputVolume.get()
        outVol = Volume()
        outVol.setSamplingRate(inputVolume.getSamplingRate())
        ImageHandler().scaleSplines(os.path.join(out_path_vol, f"decoded_volume_00.mrc"),
                                    os.path.join(out_path_vol, f"decoded_volume_00.mrc"),
                                    finalDimension=inputVolume.getXDim(), overwrite=True)

        ImageHandler().setSamplingRate(os.path.join(out_path_vol, f"decoded_volume_00.mrc"),
                                       inputVolume.getSamplingRate())

        outVol.setLocation(os.path.join(out_path_vol, f"decoded_volume_00.mrc"))

        self._defineOutputs(outputVolumes=outVol)
        self._defineTransformRelation(inputVolume, outVol)

    # --------------------------- INFO functions -----------------------------
    def _summary(self):
        summary = []
        logFile = os.path.abspath(self._getLogsPath()) + "/run.stdout"
        with open(logFile, "r") as fi:
            for ln in fi:
                if ln.startswith("GPU memory has"):
                    summary.append(ln)
                    break
        return summary

    # ----------------------- VALIDATE functions -----------------------
    def _validate(self):
        """ Try to find errors on define params. """
        errors = []

        mask = self.inputVolumeMask.get()

        if mask is not None:
            data = ImageHandler(mask.getFileName()).getData()
            if not np.all(np.logical_and(data >= 0, data <= 1)):
                errors.append("Mask provided is not binary. Please, provide a binary mask")

        return errors

    def _warnings(self):
        warnings = []

        return warnings

    # --------------------------- UTILS functions -----------------------

    def _getXmippFileName(self, filename):
        if getExt(filename) == ".mrc":
            filename += ":mrc"
        return filename