# **************************************************************************
# *
# * Authors:     Eduardo García Delgado (eduardo.garcia@cnb.csic.es) [1]
# *              David Herreros Calero (dherreos@cnb.csic.es) [1]
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC [1]
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************

import os
import numpy as np

import pyworkflow.protocol.params as params
from pyworkflow import VERSION_1
import pyworkflow.utils as pwutils

from pwem.protocols import ProtAnalysis3D, ProtFlexBase
from pwem.objects import Volume, ParticleFlex

import hax
import hax.constants as const

class JaxProtTrainFlexConsensus(ProtAnalysis3D, ProtFlexBase):
    """
    Protocol to train a FlexConsensus network.

    AI Generated:

    Train – FlexConsensus (JaxProtTrainFlexConsensus) — User Manual
        Overview

        The Train – FlexConsensus protocol learns a shared latent
        conformational space from multiple flexible cryo-EM particle
        datasets. Its purpose is to integrate several latent spaces,
        typically generated by different flexible reconstruction methods,
        into a common consensus representation.

        In practical terms, the protocol takes several input particle sets,
        each containing latent conformational coordinates, and trains a
        neural network that projects them into a unified space where the
        structural variability can be compared directly.

        For biological users, this protocol becomes particularly useful
        when multiple heterogeneous reconstructions of the same molecular
        system have been generated independently. It allows comparison of
        conformational landscapes across methods, datasets, or experimental
        conditions in a common coordinate system.

        Inputs and General Workflow

        The protocol requires multiple input sets of flexible particles.

        Each input set must already contain latent coordinates obtained
        from an upstream flexible reconstruction protocol.

        The workflow consists of three main stages.

        First, the protocol extracts the latent coordinates from every
        input particle set and stores them as independent latent-space
        files.

        Second, the FlexConsensus neural network is trained using all
        input latent spaces simultaneously. During this step, the model
        learns a consensus latent representation that captures the common
        conformational variability across all input datasets.

        Third, the trained model predicts consensus coordinates for every
        particle in every input set and generates new output particle sets
        containing those coordinates.

        Latent Space Dimension

        A key parameter of the protocol is the dimensionality of the
        consensus latent space.

        By default, this dimension is determined automatically. In this
        case, the protocol uses the minimum latent dimensionality among
        all input spaces.

        This default behavior is generally appropriate because it ensures
        that all datasets can be represented consistently in the common
        space.

        Advanced users may instead define the latent dimensionality
        manually.

        From a biological perspective, smaller latent spaces tend to
        capture the dominant collective conformational motions, whereas
        larger latent spaces may retain finer structural variability but
        may also introduce unnecessary complexity.

        Network Training

        The central stage of the protocol is the training of the
        FlexConsensus neural network.

        During training, the network receives several latent spaces as
        input and learns how to project them into a common manifold.

        Three main hyperparameters control this optimization.

        Number of epochs

        This parameter controls how long the network is trained.

        Increasing the number of epochs may improve convergence, but
        excessive training can lead to overfitting.

        Batch size

        Batch size determines how many latent samples are processed
        simultaneously.

        Larger batch sizes improve computational efficiency and GPU
        throughput, while smaller batch sizes may capture more local
        structural variability.

        Learning rate

        The learning rate controls optimization speed and stability.

        Values that are too large may cause unstable optimization,
        whereas very small values may slow convergence considerably.

        When training becomes unstable, decreasing the learning rate is
        often the most effective first adjustment.

        Fine-Tuning Previous Models

        The protocol optionally allows fine-tuning of a previously
        trained FlexConsensus network.

        When enabled, training does not start from scratch. Instead,
        previously learned consensus representations are reused and
        further refined using the new data.

        This can be particularly useful when:

            - extending previous analyses with new particle sets,
            - refining an existing consensus space,
            - incrementally integrating additional datasets.

        Outputs and Their Interpretation

        For each input particle set, the protocol produces a new output
        set of flexible particles.

        Each output particle contains:

            - consensus latent coordinates,
            - consensus error,
            - representation error.

        Consensus coordinates

        These coordinates define the position of the particle in the
        shared conformational space.

        Particles originating from different input datasets can now be
        compared directly.

        Consensus error

        This value indicates how well the learned consensus model
        represents the particle in the shared latent space.

        Representation error

        This value measures how accurately the original latent
        representation can be reconstructed through the consensus model.

        From a biological perspective, these error metrics can be useful
        to identify:

            - particles poorly explained by the consensus model,
            - structural states unique to a specific dataset,
            - regions of disagreement between reconstruction methods.

        Practical Recommendations

        In most biological applications, the default automatic latent
        dimensionality is a good starting point.

        If several input datasets are believed to describe essentially
        the same conformational landscape, FlexConsensus can provide a
        very useful way to compare them directly.

        When integrating datasets generated with very different flexible
        reconstruction methods, inspecting the consensus and
        representation errors is especially important, since high errors
        may indicate that some conformational states are not shared
        across all datasets.

        Larger batch sizes are often efficient for routine analyses, but
        smaller batches may be beneficial when subtle local variability
        is of particular biological interest.

        Final Perspective

        For cryo-EM users, FlexConsensus is not simply a dimensionality
        reduction tool.

        It provides a principled framework to compare heterogeneous
        conformational spaces across multiple datasets in a common
        coordinate system.

        When used carefully, this protocol can reveal whether different
        reconstruction strategies, datasets, or biochemical conditions
        capture the same structural variability or instead highlight
        distinct conformational behaviors.
    """
    _label = 'train - FlexConsensus'
    _lastUpdateVersion = VERSION_1

    # --------------------------- DEFINE param functions --------------------------------------------
    def _defineParams(self, form):
        form.addSection(label='Input')
        form.addHidden(params.USE_GPU, params.BooleanParam, default=True,
                       label="Use GPU for execution",
                       help="This protocol has both CPU and GPU implementation.\
                                 Select the one you want to use.")

        form.addHidden(params.GPU_LIST, params.StringParam, default='0',
                       expertLevel=params.LEVEL_ADVANCED,
                       label="Choose GPU IDs",
                       help="Add a list of GPU devices that can be used")

        form.addParam('inputSets', params.MultiPointerParam, label="Input particles", pointerClass='SetOfParticlesFlex',
                      important=True)

        group = form.addGroup("Latent Space", expertLevel=params.LEVEL_ADVANCED)
        group.addParam('setManual', params.BooleanParam, default=False, label='Set manually latent space dimension?',
                       expertLevel=params.LEVEL_ADVANCED,
                       help="If set to No, consensus space dimensions will be set automatically to the minimum dimension "
                            "of all the input spaces.")

        group.addParam('latDim', params.IntParam, label='Latent space dimension',
                       expertLevel=params.LEVEL_ADVANCED, condition="setManual",
                       help="Dimension of the FlexConsensus bottleneck (latent space dimension)")

        form.addSection(label='Network')
        form.addParam('fineTune', params.BooleanParam, default=False, label='Fine tune previous network?',
                      help='When set to Yes, you will be able to provide a previously trained FlexConsensus network to refine it with new '
                           'data. If set to No, you will train a new FlexConsensus network from scratch.')

        group = form.addGroup("Network hyperparameters")
        group.addParam('epochs', params.IntParam, default=100, label='Number of training epochs')

        group.addParam('batch_size', params.IntParam, default=1024, label='Number of samples in batch',
                       help="Determines how many images will be load in the GPU at any moment during training (set by "
                            "default to 1024 - you can control GPU memory usage easily by tuning this parameter to fit your "
                            "hardware requirements - we recommend using tools like nvidia-smi to monitor and/or measure "
                            "memory usage and adjust this value - keep also in mind that bigger batch sizes might be "
                            "less precise when looking for very local motions")

        group.addParam('learningRate', params.FloatParam, default=1e-5, label='Learning rate',
                       help="The learning rate (lr) sets the speed of learning. Think of the model as trying to find the "
                            "lowest point in a valley; the lr is the size of the step it takes on each attempt. A large "
                            "lr (e.g., 0.01) is like taking huge leaps — it's fast but can be unstable, overshoot the "
                            "lowest point, or cause NAN errors. A small lr (e.g., 1e-6) is like taking tiny shuffles — "
                            "it's stable but very slow and might get stuck before reaching the bottom. A good default is "
                            "often 0.0001. If training fails or errors explode, try making the lr 10 times smaller (e.g., "
                            "0.001 --> 0.0001).")

        form.addParallelSection(threads=4, mpi=0)

    # --------------------------- INSERT steps functions --------------------------------------------
    def _insertAllSteps(self):
        self._insertFunctionStep(self.convertInputStep)
        self._insertFunctionStep(self.trainingPredictStep)
        self._insertFunctionStep(self.createOutputStep)

    def convertInputStep(self):
        data_path = self._getExtraPath("data")
        if not os.path.isdir(data_path):
            pwutils.makePath(data_path)

        idx = 0
        for inputSet in self.inputSets:
            particle_set = inputSet.get()

            progName = particle_set.getFlexInfo().getProgName()
            data_file = progName + f"_{idx}.npy"

            z_flex = []
            for particle in particle_set.iterItems():
                z_flex.append(particle.getZFlex())
            z_flex = np.vstack(z_flex)
            latent_space = os.path.join(data_path, data_file)
            np.save(latent_space, z_flex)

            idx += 1

    def trainingPredictStep(self):
        data_path = self._getExtraPath("data")
        out_path = self._getExtraPath()
        batch_size = self.batch_size.get()
        learningRate = self.learningRate.get()
        epochs = self.epochs.get()
        lat_dim = self.latDim.get()

        input_spaces = []
        idx = 0
        for inputSet in self.inputSets:
            particle_set = inputSet.get()

            progName = particle_set.getFlexInfo().getProgName()
            input_spaces.append(progName + f"_{idx}:" + os.path.join(data_path, progName + f"_{idx}.npy"))

            idx += 1

        args = ("--input_space %s --epochs %d --batch_size %d --output_path %s --learning_rate %s " %
                (" ".join(input_spaces), epochs, batch_size, out_path, learningRate))

        if self.setManual:
            args += '--lat_dim %d ' % lat_dim

        if self.useGpu.get():
            gpu = str(self.getGpuList()[0])
        else:
            gpu = None

        program = hax.Plugin.getProgram("flexconsensus", gpu)
        if not os.path.isdir(self._getExtraPath("FlexConsensus")):
            self.runJob(program,
                        args + f'--mode train --reload {self._getExtraPath()}'
                        if self.fineTune else args + '--mode train',
                        numberOfMpi=1)
        self.runJob(program, args + f'--mode predict --reload {self._getExtraPath()}', numberOfMpi=1)

    def createOutputStep(self):
        idx = 0
        for inputSet in self.inputSets:
            inputSet = inputSet.get()
            progName = inputSet.getFlexInfo().getProgName()

            outputSet = self._createSetOfParticlesFlex(progName=progName, suffix=f"_{idx}")
            outputSet.copyInfo(inputSet)
            outputSet.setHasCTF(inputSet.hasCTF())
            outputSet.setAlignmentProj()

            consensus_space = np.load(self._getExtraPath(progName + f"_{idx}_consensus.npy"))
            consensus_space_error = np.load(self._getExtraPath(progName + f"_{idx}_consensus_error.npy"))
            representation_error = np.load(self._getExtraPath(progName + f"_{idx}_representation_error.npy"))

            idl = 0
            for particle in inputSet.iterItems():
                outParticle = ParticleFlex(progName=const.FLEXCONSENSUS)
                outParticle.copyInfo(particle)
                outParticle.setZRed(consensus_space[idl])
                outParticle.getFlexInfo().setAttr("consensus_error", float(consensus_space_error[idl]))
                outParticle.getFlexInfo().setAttr("representation_error", float(representation_error[idl]))
                outputSet.append(outParticle)
                idl += 1

            self._defineOutputs(**{f"outputParticles_{progName}_{idx}": outputSet})
            self._defineTransformRelation(inputSet, outputSet)

            idx += 1

        # --------------------------- INFO functions -----------------------------

    def _summary(self):
        summary = []
        logFile = os.path.abspath(self._getLogsPath()) + "/run.stdout"
        with open(logFile, "r") as fi:
            for ln in fi:
                if ln.startswith("GPU memory has"):
                    summary.append(ln)
                    break
        return summary

    # --------------------------- UTILS functions --------------------------------------------

    # ----------------------- VALIDATE functions ----------------------------------------