# **************************************************************************
# *
# * Authors:     David Herreros Calero (dherreos@cnb.csic.es) [1]
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC [1]
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************

import os
import numpy as np

from xmipp_metadata.metadata import XmippMetaData
from xmipp_metadata.image_handler import ImageHandler

import pyworkflow.protocol.params as params
from pyworkflow.object import Float
from pyworkflow.utils.path import moveFile
from pyworkflow import VERSION_1
from pyworkflow.utils import getExt, makePath

from pwem.protocols import ProtAnalysis3D, ProtFlexBase
from pwem.objects import Volume, Particle

import xmipp3
from xmipp3.convert import writeSetOfParticles, matrixFromGeometry

import hax

class JaxProtFilterLatents(ProtAnalysis3D, ProtFlexBase):
    """
    Automatically filters latent conformational spaces by identifying and
    removing outlier particles from a latent embedding. The protocol keeps
    particles whose latent coordinates are locally consistent with the
    dominant conformational landscape.

    AI Generated:

    Filter Latent Space (JaxProtFilterLatents) — User Manual
        Overview

        The Filter Latent Space protocol automatically removes outlier
        particles from a latent conformational embedding. Its main goal
        is to retain particles that belong to the coherent structural
        manifold while excluding those whose latent coordinates are
        unusually distant from their local neighbourhood.

        In cryo-EM flexibility analysis, latent embeddings often contain
        particles that arise from poor reconstructions, low-quality
        images, rare artifacts, or isolated regions of the latent space.
        These particles can distort downstream analyses such as
        clustering, trajectory estimation, interpolation, or
        visualization. This protocol helps clean the latent landscape
        before further interpretation.

        Inputs and General Workflow

        The protocol requires a SetOfParticlesFlex object as input.
        Each particle must contain latent coordinates generated by a
        compatible flexibility-analysis method.

        The workflow proceeds in three main steps.

        First, the latent coordinates of all particles are extracted and
        saved into an internal numerical representation.

        Second, an automatic filtering procedure analyzes the local
        neighbourhood of every latent sample. For each particle, the
        algorithm evaluates how consistent its position is with nearby
        neighbours in the conformational manifold.

        Third, only particles satisfying the selected filtering
        criterion are preserved and written into a new output particle
        set.

        Local Neighbourhood Analysis

        The key filtering principle is based on neighbourhood
        consistency.

        For each latent coordinate, the algorithm searches for a
        user-defined number of nearest neighbours. This local structure
        provides a measure of whether a particle belongs to a coherent
        region of the conformational landscape.

        Smaller neighbour values emphasize very local geometric
        consistency. This is often useful when subtle motions or local
        conformational branches are biologically important.

        Larger neighbour values capture broader manifold organization.
        These settings are more appropriate when the user wants to
        preserve global latent-space continuity rather than highly local
        features.

        Outlier Detection

        Outliers are detected using a Z-score–based distance criterion.

        The outliers threshold determines how far a latent coordinate
        may deviate from its neighbourhood before being rejected.

        Lower thresholds produce stricter filtering. They remove more
        particles and preserve only the most tightly supported regions
        of the latent manifold.

        Higher thresholds are more permissive. They retain broader
        conformational diversity but may preserve isolated or noisy
        particles.

        Biologically, aggressive filtering may remove rare but genuine
        conformational states, while permissive filtering may preserve
        unwanted artifacts. The threshold should therefore be selected
        according to the scientific goal.

        GPU and Batch Processing

        The protocol supports GPU execution.

        The batch size controls how many latent samples are processed at
        the same time. Larger values usually improve throughput but
        require more GPU memory.

        In practice, users often adjust batch size according to
        available hardware resources. Monitoring GPU memory usage is
        recommended when processing large datasets.

        Output Generation

        The output is a new SetOfParticlesFlex object containing only
        particles that passed the filtering criterion.

        The protocol preserves the original particle metadata, including
        acquisition information, CTF information, and flexible-analysis
        metadata.

        No latent coordinates are modified during filtering. The
        protocol only removes particles identified as outliers.

        Biological Interpretation

        The filtered output represents a cleaner conformational
        landscape with reduced influence from isolated latent points.

        In biological terms, this often improves the stability of
        downstream analyses such as:

        - conformational clustering,
        - latent-space interpolation,
        - trajectory extraction,
        - state annotation,
        - manifold visualization.

        However, users should remember that not all sparse regions are
        necessarily artifacts. Rare functional intermediates may also
        appear as isolated points. For this reason, automatic filtering
        should always be interpreted in the context of the biological
        system.

        Practical Recommendations

        For exploratory work, moderate neighbour values and a threshold
        near the default usually provide a reasonable starting point.

        If the latent space appears noisy or highly fragmented, stricter
        thresholds can improve robustness.

        If the dataset contains suspected continuous heterogeneity or
        rare structural intermediates, more permissive filtering is
        often preferable to avoid removing biologically meaningful
        particles.

        Final Perspective

        Filtering latent spaces is often a valuable preprocessing step
        before interpreting structural heterogeneity.

        By removing isolated latent outliers while preserving coherent
        conformational regions, this protocol helps produce a more
        reliable representation of the underlying structural landscape.
    """
    _label = 'filter latent space'
    _lastUpdateVersion = VERSION_1

    # --------------------------- DEFINE param functions -----------------------
    def _defineParams(self, form):
        form.addSection(label='Input')
        form.addHidden(params.USE_GPU, params.BooleanParam, default=True,
                       label="Use GPU for execution",
                       help="This protocol has both CPU and GPU implementation.\
                                 Select the one you want to use.")

        form.addHidden(params.GPU_LIST, params.StringParam, default='0',
                       expertLevel=params.LEVEL_ADVANCED,
                       label="Choose GPU IDs",
                       help="Add a list of GPU devices that can be used")

        group = form.addGroup("Data")
        group.addParam('inputParticles', params.PointerParam, label="Input particles",
                       pointerClass='SetOfParticlesFlex', important=True)

        group.addParam('batchSize', params.IntParam, default=1024, label='Number of images in batch',
                       help="Determines how many images will be load in the GPU at any moment during training (set by "
                            "default to 1024 - you can control GPU memory usage easily by tuning this parameter to fit your "
                            "hardware requirements - we recommend using tools like nvidia-smi to monitor and/or measure "
                            "memory usage and adjust this value - keep also in mind that bigger batch sizes might be "
                            "less precise when looking for very local motions")

        group = form.addGroup("Filter parameters")
        group.addParam("neighbours", params.IntParam, default=10, label="Number of neighbours",
                      help="Number of nearest neighbours to be search for each landscape sample. Smaller "
                           "values will better approximate the locality features of a sample, while global "
                           "values will capture more general landscape features.")

        group.addParam('outliersThreshold', params.FloatParam, default=1.0,
                      label="Outliers distance threshold",
                      help='Z-Score value from 0 to infinite. Only coordinates with a Z-Score smaller than '
                           'or equal to the threshold will be kept in the output')

    # --------------------------- INSERT steps functions -----------------------
    def _insertAllSteps(self):
        self._insertFunctionStep(self.writeLatentsStep)
        self._insertFunctionStep(self.filterLatentsStep)
        self._insertFunctionStep(self.createOutputStep)

    def writeLatentsStep(self):
        inputParticles = self.inputParticles.get()

        # Save latents to .npy file
        latents = []
        for particle in inputParticles.iterItems():
            latents.append(particle.getZFlex())
        latents = np.vstack(latents)
        latents_file = self._getExtraPath("latents.npy")
        np.save(latents_file, latents)


    def filterLatentsStep(self):
        latents_file = self._getExtraPath("latents.npy")
        thr = self.outliersThreshold.get()
        n_neighbours = self.neighbours.get()
        batch_size = self.batchSize.get()


        args = (f"--latents {latents_file} --thr {thr} --n_neighbours {n_neighbours} --return_ids "
                f"--batch_size {batch_size} --output_path {self._getExtraPath()}")

        if self.useGpu.get():
            gpu = str(self.getGpuList()[0])
        else:
            gpu = None

        program = hax.Plugin.getProgram("filter_latents", gpu)
        self.runJob(program, args, numberOfMpi=1)

    def createOutputStep(self):
        inputSet = self.inputParticles.get()

        filter_ids = np.load(self._getExtraPath("filtered_latents.npy")).astype(int)
        particle_ids = list(inputSet.getIdSet())

        partSet = self._createSetOfParticlesFlex(progName=inputSet.getFlexInfo().getProgName())
        partSet.copyInfo(inputSet)
        partSet.setHasCTF(inputSet.hasCTF())

        for idx in filter_ids:
            partSet.append(inputSet[particle_ids[idx]].clone())

        self._defineOutputs(outputParticles=partSet)
        self._defineTransformRelation(inputSet, partSet)


    # --------------------------- INFO functions -----------------------------
    def _summary(self):
        summary = []
        return summary

    # ----------------------- VALIDATE functions -----------------------
    def _validate(self):
        """ Try to find errors on define params. """
        errors = []
        return errors

    def _warnings(self):
        warnings = []
        return warnings
